# Ingresar por teclado los precios correspondientes a cinco artículos y las cantidades vendidas de cada uno de ellos. Calcular e imprimir el importe total de ventas de cada uno y un importe total de lo vendido.
producto1=input("Ingresa el nombre de el producto: ")
precio1=float(input("Precio del producto: "))
cantidad1=int(input("Ingresa la cantidad de productos: "))
producto2=input("Ingresa el nombre de el producto: ")
precio2=float(input("Precio del producto: "))
cantidad2=int(input("Ingresa la cantidad de productos: "))
producto3=input("Ingresa el nombre de el producto: ")
precio3=float(input("Precio del producto: "))
cantidad3=int(input("Ingresa la cantidad de productos: "))
producto4=input("Ingresa el nombre de el producto: ")
precio4=float(input("Precio del producto: "))
cantidad4=int(input("Ingresa la cantidad de productos: "))
producto5=input("Ingresa el nombre de el producto: ")
precio5=float(input("Precio del producto: "))
cantidad5=int(input("Ingresa la cantidad de productos: "))
total1=float(cantidad1*precio1)
total2=float(cantidad2*precio2)
total3=float(cantidad3*precio3)
total4=float(cantidad4*precio4)
total5=float(cantidad5*precio5)
totalgeneral=float(total1+total2+total3+total4+total5)
print(f"{producto1}- ${total1}")
print(f"{producto2}- ${total2}")
print(f"{producto3}- ${total3}")
print(f"{producto4}- ${total4}")
print(f"{producto5}- ${total5}")
print(f"El total de las ventas es de: {totalgeneral}")